spring.application.name=dish-app

spring.datasource.url=jdbc:postgresql://localhost:5432/dishdb
spring.datasource.username=postgres
spring.datasource.password=chayma
server.port=8082
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


image.upload.dir=images


